name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            args: "chrome test1.js"